# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Read package version
      run: PACKAGE_VERSION=$(head -n 1 version.txt) && echo $PACKAGE_VERSION && echo ::set-env name=PACKAGE_VERSION::$PACKAGE_VERSION
    - name: Read changelog
      run: CHANGELOG=$(tail -n+3 version.txt) && echo $CHANGELOG && echo ::set-env name=CHANGELOG::$CHANGELOG
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Add execution privileges
      run: chmod +x ./gradlew
      working-directory: ./backend/burning-okr
    - name: Test
      run: ./gradlew check
      working-directory: ./backend/burning-okr
    - name: Build jar
      run: ./gradlew -PprojVersion="$PACKAGE_VERSION" bootJar
      working-directory: ./backend/burning-okr
    - name: Build war
      run: ./gradlew -PprojVersion="$PACKAGE_VERSION" bootWar
      working-directory: ./backend/burning-okr
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: backend/burning-okr/burning-okr-app/build/libs
        
    - name: Npm Setup
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Npm Install
      run: npm install
      working-directory: ./frontend
    - name: Npm Build
      run: npm run build-prod
      working-directory: ./frontend
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.PACKAGE_VERSION }}
        release_name: Release ${{ env.PACKAGE_VERSION }}
        body: ${{ env.CHANGELOG }}
        draft: false
        prerelease: true
    - name: Upload Release Jar
      id: upload-release-jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./backend/burning-okr/burning-okr-app/build/libs/burning-okr-app-${{ env.PACKAGE_VERSION }}.jar
        asset_name: burning-okr-app-${{ env.PACKAGE_VERSION }}.jar
        asset_content_type: application/jar 
    - name: Upload Release War
      id: upload-release-war
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./backend/burning-okr/burning-okr-app/build/libs/burning-okr-app-${{ env.PACKAGE_VERSION }}.war
        asset_name: burning-okr-app-${{ env.PACKAGE_VERSION }}.war
        asset_content_type: application/war
    
